/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Auth API
 * API для аутентификации пользователей
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DocsAccessRequest,
  DocsForgotPasswordRequest,
  DocsLoginRequest,
  DocsRefreshRequest,
  DocsRegisterRequest,
  DocsResetPasswordRequest,
  DocsSuccessResponseWithoutData,
  GetAuthMe200,
  PostAuthConfirmAccountParams,
  PostAuthLogin200,
  PostAuthRefresh200,
  PostAuthRegister200,
  PostAuthResetPasswordParams
} from './auth.schemas';




  export const getAuthAPI = () => {
/**
 * Проверяет доступ к заданному маршруту на основе роли
 * @summary Проверка прав доступа
 */
const postAuthAccess = <TData = AxiosResponse<DocsSuccessResponseWithoutData>>(
    docsAccessRequest: DocsAccessRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://cicada-chess.ru:8081/auth/access`,
      docsAccessRequest,options
    );
  }

/**
 * Проверяет валидность переданного access-токена
 * @summary Проверка токена
 */
const getAuthCheck = <TData = AxiosResponse<DocsSuccessResponseWithoutData>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://cicada-chess.ru:8081/auth/check`,options
    );
  }

/**
 * Активирует аккаунт пользователя по токену
 * @summary Подтверждение аккаунта
 */
const postAuthConfirmAccount = <TData = AxiosResponse<DocsSuccessResponseWithoutData>>(
    params: PostAuthConfirmAccountParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://cicada-chess.ru:8081/auth/confirm-account`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Отправляет ссылку для восстановления доступа
 * @summary Восстановление пароля
 */
const postAuthForgotPassword = <TData = AxiosResponse<DocsSuccessResponseWithoutData>>(
    docsForgotPasswordRequest: DocsForgotPasswordRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://cicada-chess.ru:8081/auth/forgot-password`,
      docsForgotPasswordRequest,options
    );
  }

/**
 * Аутентифицирует пользователя и выдаёт JWT-токены
 * @summary Вход пользователя
 */
const postAuthLogin = <TData = AxiosResponse<PostAuthLogin200>>(
    docsLoginRequest: DocsLoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://cicada-chess.ru:8081/auth/login`,
      docsLoginRequest,options
    );
  }

/**
 * Завершает сессию пользователя
 * @summary Выход пользователя
 */
const getAuthLogout = <TData = AxiosResponse<DocsSuccessResponseWithoutData>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://cicada-chess.ru:8081/auth/logout`,options
    );
  }

/**
 * Возвращает информацию о пользователе, если токен действителен
 * @summary Получение информации о пользователе по access-токену
 */
const getAuthMe = <TData = AxiosResponse<GetAuthMe200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://cicada-chess.ru:8081/auth/me`,options
    );
  }

/**
 * Обновляет access-токен с помощью refresh-токена
 * @summary Обновление токена
 */
const postAuthRefresh = <TData = AxiosResponse<PostAuthRefresh200>>(
    docsRefreshRequest: DocsRefreshRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://cicada-chess.ru:8081/auth/refresh`,
      docsRefreshRequest,options
    );
  }

/**
 * Регистрирует нового пользователя
 * @summary Регистрация пользователя
 */
const postAuthRegister = <TData = AxiosResponse<PostAuthRegister200>>(
    docsRegisterRequest: DocsRegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://cicada-chess.ru:8081/auth/register`,
      docsRegisterRequest,options
    );
  }

/**
 * Сбрасывает пароль по ссылке для восстановления
 * @summary Сброс пароля
 */
const postAuthResetPassword = <TData = AxiosResponse<DocsSuccessResponseWithoutData>>(
    docsResetPasswordRequest: DocsResetPasswordRequest,
    params: PostAuthResetPasswordParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://cicada-chess.ru:8081/auth/reset-password`,
      docsResetPasswordRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

return {postAuthAccess,getAuthCheck,postAuthConfirmAccount,postAuthForgotPassword,postAuthLogin,getAuthLogout,getAuthMe,postAuthRefresh,postAuthRegister,postAuthResetPassword}};
export type PostAuthAccessResult = AxiosResponse<DocsSuccessResponseWithoutData>
export type GetAuthCheckResult = AxiosResponse<DocsSuccessResponseWithoutData>
export type PostAuthConfirmAccountResult = AxiosResponse<DocsSuccessResponseWithoutData>
export type PostAuthForgotPasswordResult = AxiosResponse<DocsSuccessResponseWithoutData>
export type PostAuthLoginResult = AxiosResponse<PostAuthLogin200>
export type GetAuthLogoutResult = AxiosResponse<DocsSuccessResponseWithoutData>
export type GetAuthMeResult = AxiosResponse<GetAuthMe200>
export type PostAuthRefreshResult = AxiosResponse<PostAuthRefresh200>
export type PostAuthRegisterResult = AxiosResponse<PostAuthRegister200>
export type PostAuthResetPasswordResult = AxiosResponse<DocsSuccessResponseWithoutData>
