/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 */
export interface DocsAccessRequest {
  role?: number;
  url?: string;
}

export interface DocsAccessToken {
  access_token: string;
  expires_in: number;
  token_type: string;
}

export interface DocsErrorResponse {
  message?: string;
  status?: string;
}

export interface DocsForgotPasswordRequest {
  email?: string;
}

export interface DocsLoginRequest {
  email?: string;
  password?: string;
}

export interface DocsRefreshRequest {
  refresh_token?: string;
}

export interface DocsResetPasswordRequest {
  new_password?: string;
  token?: string;
}

export interface DocsSuccessResponse {
  data?: unknown;
  message?: string;
  status?: string;
}

export interface DocsSuccessResponseWithoutData {
  message?: string;
  status?: string;
}

export interface DocsToken {
  access_expires_in?: number;
  access_token?: string;
  refresh_expires_in?: number;
  refresh_token?: string;
  token_type?: string;
}

export type PostAuthLogin200AllOf = {
  data?: DocsToken;
};

export type PostAuthLogin200 = DocsSuccessResponse & PostAuthLogin200AllOf;

export type PostAuthRefresh200AllOf = {
  data?: DocsAccessToken;
};

export type PostAuthRefresh200 = DocsSuccessResponse & PostAuthRefresh200AllOf;

