/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DocsChangePasswordRequest,
  DocsCreateUserRequest,
  DocsSuccessResponse,
  DocsSuccessResponseWithoutData,
  DocsUpdateInfoRequest,
  DocsUpdateRatingRequest,
  GetUsers200,
  GetUsersId200,
  GetUsersParams,
  PatchUsersId200,
  PostUsersCreate201
} from './users.schemas';




  export const get = () => {
/**
 * Возвращает список пользователей с поддержкой пагинации и сортировки
 * @summary Получение списка пользователей
 */
const getUsers = <TData = AxiosResponse<GetUsers200>>(
    params?: GetUsersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://217.114.11.158:8080/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Создаёт нового пользователя
 * @summary Создание пользователя
 */
const postUsersCreate = <TData = AxiosResponse<PostUsersCreate201>>(
    docsCreateUserRequest: DocsCreateUserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://217.114.11.158:8080/users/create`,
      docsCreateUserRequest,options
    );
  }

/**
 * Возвращает данные пользователя по его идентификатору
 * @summary Получение пользователя по ID
 */
const getUsersId = <TData = AxiosResponse<GetUsersId200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://217.114.11.158:8080/users/${id}`,options
    );
  }

/**
 * Удаляет пользователя по ID
 * @summary Удаление пользователя
 */
const deleteUsersId = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://217.114.11.158:8080/users/${id}`,options
    );
  }

/**
 * Изменяет информацию о пользователе (email, username и т.д.)
 * @summary Обновление данных пользователя
 */
const patchUsersId = <TData = AxiosResponse<PatchUsersId200>>(
    id: string,
    docsUpdateInfoRequest: DocsUpdateInfoRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `http://217.114.11.158:8080/users/${id}`,
      docsUpdateInfoRequest,options
    );
  }

/**
 * Изменяет пароль пользователя при наличии корректных старого пароля
 * @summary Изменение пароля
 */
const postUsersIdChangePassword = <TData = AxiosResponse<DocsSuccessResponseWithoutData>>(
    id: string,
    docsChangePasswordRequest: DocsChangePasswordRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://217.114.11.158:8080/users/${id}/change-password`,
      docsChangePasswordRequest,options
    );
  }

/**
 * Возвращает текущий рейтинг пользователя
 * @summary Получение рейтинга
 */
const getUsersIdRating = <TData = AxiosResponse<DocsSuccessResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://217.114.11.158:8080/users/${id}/rating`,options
    );
  }

/**
 * Переключает признак активности пользователя
 * @summary Смена статуса активности
 */
const postUsersIdToggleActive = <TData = AxiosResponse<DocsSuccessResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://217.114.11.158:8080/users/${id}/toggle-active`,undefined,options
    );
  }

/**
 * Увеличивает или уменьшает рейтинг пользователя на указанную величину
 * @summary Обновление рейтинга
 */
const postUsersIdUpdateRating = <TData = AxiosResponse<DocsSuccessResponse>>(
    id: string,
    docsUpdateRatingRequest: DocsUpdateRatingRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://217.114.11.158:8080/users/${id}/update-rating`,
      docsUpdateRatingRequest,options
    );
  }

return {getUsers,postUsersCreate,getUsersId,deleteUsersId,patchUsersId,postUsersIdChangePassword,getUsersIdRating,postUsersIdToggleActive,postUsersIdUpdateRating}};
export type GetUsersResult = AxiosResponse<GetUsers200>
export type PostUsersCreateResult = AxiosResponse<PostUsersCreate201>
export type GetUsersIdResult = AxiosResponse<GetUsersId200>
export type DeleteUsersIdResult = AxiosResponse<void>
export type PatchUsersIdResult = AxiosResponse<PatchUsersId200>
export type PostUsersIdChangePasswordResult = AxiosResponse<DocsSuccessResponseWithoutData>
export type GetUsersIdRatingResult = AxiosResponse<DocsSuccessResponse>
export type PostUsersIdToggleActiveResult = AxiosResponse<DocsSuccessResponse>
export type PostUsersIdUpdateRatingResult = AxiosResponse<DocsSuccessResponse>
