/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * User API
 * API для управления пользователями
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  DocsChangePasswordRequest,
  DocsCreateUserRequest,
  DocsSuccessResponse,
  DocsSuccessResponseWithoutData,
  DocsUpdateInfoRequest,
  DocsUpdateProfileRequest,
  DocsUpdateRatingRequest,
  GetProfile200,
  GetUsers200,
  GetUsersId200,
  GetUsersParams,
  PatchProfile200,
  PatchUsersId200,
  PostProfileAvatar200,
  PostProfileAvatarBody,
  PostProfileCreateId200,
  PostUsersCreate201
} from './users.schemas';




  export const getUserAPI = () => {
/**
 * Возвращает профиль текущего аутентифицированного пользователя
 * @summary Получение профиля пользователя
 */
const getProfile = <TData = AxiosResponse<GetProfile200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://cicada-chess.ru:8080/profile`,options
    );
  }

/**
 * Обновляет профиль текущего аутентифицированного пользователя
 * @summary Обновление профиля пользователя
 */
const patchProfile = <TData = AxiosResponse<PatchProfile200>>(
    docsUpdateProfileRequest: DocsUpdateProfileRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `https://cicada-chess.ru:8080/profile`,
      docsUpdateProfileRequest,options
    );
  }

/**
 * Загружает аватар для текущего аутентифицированного пользователя
 * @summary Загрузка аватара
 */
const postProfileAvatar = <TData = AxiosResponse<PostProfileAvatar200>>(
    postProfileAvatarBody: PostProfileAvatarBody, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
formData.append('avatar', postProfileAvatarBody.avatar)

    return axios.post(
      `https://cicada-chess.ru:8080/profile/avatar`,
      formData,options
    );
  }

/**
 * Создает профиль для пользователя по его идентификатору
 * @summary Создание профиля пользователя
 */
const postProfileCreateId = <TData = AxiosResponse<PostProfileCreateId200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://cicada-chess.ru:8080/profile/create/${id}`,undefined,options
    );
  }

/**
 * Возвращает список пользователей с поддержкой пагинации и сортировки
 * @summary Получение списка пользователей
 */
const getUsers = <TData = AxiosResponse<GetUsers200>>(
    params?: GetUsersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://cicada-chess.ru:8080/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Создаёт нового пользователя
 * @summary Создание пользователя
 */
const postUsersCreate = <TData = AxiosResponse<PostUsersCreate201>>(
    docsCreateUserRequest: DocsCreateUserRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://cicada-chess.ru:8080/users/create`,
      docsCreateUserRequest,options
    );
  }

/**
 * Возвращает данные пользователя по его идентификатору
 * @summary Получение пользователя по ID
 */
const getUsersId = <TData = AxiosResponse<GetUsersId200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://cicada-chess.ru:8080/users/${id}`,options
    );
  }

/**
 * Удаляет пользователя по ID
 * @summary Удаление пользователя
 */
const deleteUsersId = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `https://cicada-chess.ru:8080/users/${id}`,options
    );
  }

/**
 * Изменяет информацию о пользователе (email, username и т.д.)
 * @summary Обновление данных пользователя
 */
const patchUsersId = <TData = AxiosResponse<PatchUsersId200>>(
    id: string,
    docsUpdateInfoRequest: DocsUpdateInfoRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `https://cicada-chess.ru:8080/users/${id}`,
      docsUpdateInfoRequest,options
    );
  }

/**
 * Изменяет пароль пользователя при наличии корректных старого пароля
 * @summary Изменение пароля
 */
const postUsersIdChangePassword = <TData = AxiosResponse<DocsSuccessResponseWithoutData>>(
    id: string,
    docsChangePasswordRequest: DocsChangePasswordRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://cicada-chess.ru:8080/users/${id}/change-password`,
      docsChangePasswordRequest,options
    );
  }

/**
 * Возвращает текущий рейтинг пользователя
 * @summary Получение рейтинга
 */
const getUsersIdRating = <TData = AxiosResponse<DocsSuccessResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `https://cicada-chess.ru:8080/users/${id}/rating`,options
    );
  }

/**
 * Переключает признак активности пользователя
 * @summary Смена статуса активности
 */
const postUsersIdToggleActive = <TData = AxiosResponse<DocsSuccessResponse>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://cicada-chess.ru:8080/users/${id}/toggle-active`,undefined,options
    );
  }

/**
 * Увеличивает или уменьшает рейтинг пользователя на указанную величину
 * @summary Обновление рейтинга
 */
const postUsersIdUpdateRating = <TData = AxiosResponse<DocsSuccessResponse>>(
    id: string,
    docsUpdateRatingRequest: DocsUpdateRatingRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `https://cicada-chess.ru:8080/users/${id}/update-rating`,
      docsUpdateRatingRequest,options
    );
  }

return {getProfile,patchProfile,postProfileAvatar,postProfileCreateId,getUsers,postUsersCreate,getUsersId,deleteUsersId,patchUsersId,postUsersIdChangePassword,getUsersIdRating,postUsersIdToggleActive,postUsersIdUpdateRating}};
export type GetProfileResult = AxiosResponse<GetProfile200>
export type PatchProfileResult = AxiosResponse<PatchProfile200>
export type PostProfileAvatarResult = AxiosResponse<PostProfileAvatar200>
export type PostProfileCreateIdResult = AxiosResponse<PostProfileCreateId200>
export type GetUsersResult = AxiosResponse<GetUsers200>
export type PostUsersCreateResult = AxiosResponse<PostUsersCreate201>
export type GetUsersIdResult = AxiosResponse<GetUsersId200>
export type DeleteUsersIdResult = AxiosResponse<void>
export type PatchUsersIdResult = AxiosResponse<PatchUsersId200>
export type PostUsersIdChangePasswordResult = AxiosResponse<DocsSuccessResponseWithoutData>
export type GetUsersIdRatingResult = AxiosResponse<DocsSuccessResponse>
export type PostUsersIdToggleActiveResult = AxiosResponse<DocsSuccessResponse>
export type PostUsersIdUpdateRatingResult = AxiosResponse<DocsSuccessResponse>
