/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * User API
 * API для управления пользователями
 * OpenAPI spec version: 1.0
 */
export interface DocsChangePasswordRequest {
  new_password: string;
  old_password: string;
}

export interface DocsCreateUserRequest {
  email: string;
  password: string;
  username: string;
}

export interface DocsErrorResponse {
  message?: string;
  status?: string;
}

export interface DocsProfile {
  age?: number;
  avatar_url?: string;
  created_at?: string;
  description?: string;
  location?: string;
  updated_at?: string;
  user_id?: string;
}

export interface DocsSuccessResponse {
  data?: unknown;
  message?: string;
  status?: string;
}

export interface DocsSuccessResponseWithoutData {
  message?: string;
  success?: string;
}

export interface DocsUpdateInfoRequest {
  email?: string;
  is_active?: boolean;
  password?: string;
  rating?: number;
  role?: number;
  username?: string;
}

export interface DocsUpdateProfileRequest {
  age?: number;
  description?: string;
  location?: string;
}

export interface DocsUpdateRatingRequest {
  delta: number;
}

export interface DocsUser {
  created_at?: string;
  email?: string;
  id?: string;
  is_active?: boolean;
  rating?: number;
  role?: number;
  updated_at?: string;
  username?: string;
}

export type GetProfile200AllOf = {
  data?: DocsProfile;
};

export type GetProfile200 = DocsSuccessResponse & GetProfile200AllOf;

export type PatchProfile200AllOf = {
  data?: DocsProfile;
};

export type PatchProfile200 = DocsSuccessResponse & PatchProfile200AllOf;

export type PostProfileAvatarBody = {
  /** Файл аватара */
  avatar: Blob;
};

export type PostProfileAvatar200AllOf = {
  data?: DocsProfile;
};

export type PostProfileAvatar200 = DocsSuccessResponse & PostProfileAvatar200AllOf;

export type PostProfileCreateId200AllOf = {
  data?: DocsProfile;
};

export type PostProfileCreateId200 = DocsSuccessResponse & PostProfileCreateId200AllOf;

export type GetUsersParams = {
/**
 * Номер страницы
 */
page?: number;
/**
 * Количество пользователей на странице
 */
limit?: number;
/**
 * Строка поиска
 */
search?: string;
/**
 * Поле для сортировки
 */
sort_by?: string;
/**
 * Порядок сортировки (asc/desc)
 */
order?: string;
};

export type GetUsers200AllOf = {
  data?: DocsUser[];
};

export type GetUsers200 = DocsSuccessResponse & GetUsers200AllOf;

export type PostUsersCreate201AllOf = {
  data?: DocsUser;
};

export type PostUsersCreate201 = DocsSuccessResponse & PostUsersCreate201AllOf;

export type GetUsersId200AllOf = {
  data?: DocsUser;
};

export type GetUsersId200 = DocsSuccessResponse & GetUsersId200AllOf;

export type PatchUsersId200AllOf = {
  data?: DocsUser;
};

export type PatchUsersId200 = DocsSuccessResponse & PatchUsersId200AllOf;

